### ISSUE TITLE
update jenkins instance to use some sort of OIDC plugin

### ISSUE THREAD

**Issue by mrparkers** [rode/demo#66]
we need some way to perform the OIDC client credentials grant before a pipeline runs, so each step has access to a JWT that can be used for authn / authz to Rode

Might be worth evaluating this plugin: https://plugins.jenkins.io/oic-auth/

**Comment by alexashley** [comment]
Looked into the `oidc-auth` plugin and also at a few others for oauth2. Not surprisingly, they're all focused on user login and don't have any support for client credentials.

**Comment by alexashley** [comment]
Addressed in https://github.com/rode/demo-app/pull/48
